INSERT INTO tags(id,name,tag_category_id) VALUES(87,'Tegument. Tesut celular subcutanat',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(88,'Perete toracic',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(89,'Perete abdominal',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(90,'Glob ocular',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(91,'Tiroida',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(92,'Paratiroide',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(93,'Glande salivare',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(94,'Limfonoduli',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(95,'Axile',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(96,'Glande mamare',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(97,'Pleure',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(98,'Plămâni',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(99,'Cord',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(100,'Mediastin',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(101,'Ficat',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(102,'Colecist si cai biliare',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(103,'Pancreas',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(104,'Splina',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(105,'Esofag',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(106,'Stomac',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(107,'Duoden',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(108,'Jejun. Ileon',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(109,'Apendice',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(110,'Colon',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(111,'Rect. Anus',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(112,'Rinichi',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(113,'Uretere. Cai urinare',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(114,'Vezica urinara',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(115,'Suprarenale',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(116,'Uter',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(117,'Ovare',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(118,'Prostata',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(119,'Scrot. Testiculi. Epididim',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(120,'Penis',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(121,'Peritoneu. Mezenter. Cavitatea peritoneala',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(122,'Spatiul retroperitoneal',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(123,'Aorta',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(124,'Artera mezenterica. Trunchiul celiac',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(125,'Vena cava inferioară. Vene renale. Vene aferente',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(126,'Sistem venos port. Vena splenică. Venele aferente',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(127,'Vasele regiunii cervicale',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(128,'Vase periferice',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(129,'Articulatii',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(130,'Musculatura',8);
INSERT INTO tags(id,name,tag_category_id) VALUES(131,'Nervi',8);
