INSERT INTO tags(id,name,tag_category_id) VALUES(12,'Administrativ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(13,'Alergologie si imunologie clinica ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(14,'Anestezie si terapie intensiva',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(15,'Balneologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(16,'Boli infectioase',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(17,'Cardiologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(18,'Chirurgie cardiovasculara',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(19,'Chirurgie generala',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(20,'Chirurgie oro-maxilo-faciala',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(21,'Chirurgie pediatrica ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(22,'Chirurgie plastica si reparatorie ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(23,'Chirurgie toracica ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(24,'Chirurgie vasculara ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(25,'Dermatovenerologie ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(26,'Diabet zaharat nutritie si boli metabolice ',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(27,'Endocrinologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(28,'Gastroenterologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(29,'Hematologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(30,'Interne',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(31,'Medicina de familie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(32,'Medicina de laborator',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(33,'Medicina de urgenta',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(34,'Medicina muncii',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(35,'Medicina sportiva',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(36,'Nefrologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(37,'Neonatologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(38,'Neurochirurgie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(39,'Neurologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(40,'Obsterica-ginecologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(41,'Oftalmologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(42,'Oncologie medicala',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(43,'ORL',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(44,'Ortopedie pediatrica',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(45,'Ortopedie si traumatologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(46,'Pediatrie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(47,'Pneumologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(48,'Psihiatrie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(49,'Radiologie si imagistica medicala',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(50,'Recuperare, medicina fizica si balneologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(51,'Reseller',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(52,'Reumatologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(53,'Senologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(54,'Urologie',2);
INSERT INTO tags(id,name,tag_category_id) VALUES(55,'Veterinar',2);

